document.addEventListener('DOMContentLoaded', () => {
    const urlInput = document.getElementById('urlInput');
    const generateBtn = document.getElementById('generateBtn');
    const qrContainer = document.getElementById('qrContainer');
    const downloadBtn = document.getElementById('downloadBtn');
    const shareBtn = document.getElementById('shareBtn');
    let qrCodeInstance; // To hold the QRCode object for reuse

    generateBtn.addEventListener('click', () => {
        const url = urlInput.value.trim();
        if (!url || !isValidUrl(url)) {
            alert('Please enter a valid URL');
            return;
        }

        // Clear previous QR if exists
        document.getElementById('qrcode').innerHTML = '';

        // Generate QR
        qrCodeInstance = new QRCode('qrcode', {
            text: url,
            width: 200,
            height: 200,
            colorDark: '#000000',
            colorLight: '#ffffff',
            correctLevel: QRCode.CorrectLevel.H // High error correction
        });

        qrContainer.classList.remove('hidden');
    });

    downloadBtn.addEventListener('click', () => {
        if (!qrCodeInstance) return;

        // Get the canvas from the QR container
        const canvas = document.getElementById('qrcode').querySelector('canvas');
        if (!canvas) return;

        // Create download link
        const link = document.createElement('a');
        link.download = 'qrkodli.png';
        link.href = canvas.toDataURL('image/png');
        link.click();
    });

    shareBtn.addEventListener('click', async () => {
        if (!qrCodeInstance) return;

        const canvas = document.getElementById('qrcode').querySelector('canvas');
        if (!canvas) return;

        // Convert canvas to blob for sharing
        canvas.toBlob(async (blob) => {
            if (!blob) return;

            const file = new File([blob], 'qrkodli.png', { type: 'image/png' });

            if (navigator.canShare && navigator.canShare({ files: [file] })) {
                try {
                    await navigator.share({
                        files: [file],
                        title: 'QRkodli - QR Code',
                        text: 'Check out this QR code generated by QRkodli!'
                    });
                } catch (err) {
                    console.error('Share failed:', err);
                    alert('Sharing not supported or failed. Try downloading instead.');
                }
            } else {
                alert('Sharing not supported on this device. Try downloading.');
            }
        }, 'image/png');
    });

    function isValidUrl(string) {
        try {
            new URL(string);
            return true;
        } catch (_) {
            return false;
        }
    }
});